version: 2

project_name: gh-sub-issue

before:
  hooks:
    - go mod tidy

builds:
  - id: gh-sub-issue
    main: ./main.go
    binary: gh-sub-issue
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/yahsan2/gh-sub-issue/cmd.Version={{.Tag}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - format: binary
    name_template: >-
      {{ .Os }}-
      {{- if eq .Arch "amd64" }}amd64
      {{- else if eq .Arch "386" }}386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

checksum:
  name_template: 'checksums.txt'

release:
  github:
    owner: yahsan2
    name: gh-sub-issue